# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=200)),
                ('monto_UF', models.IntegerField(default=0)),
                ('plazo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TMC', models.IntegerField(default=0)),
                ('fecha_consulta', models.DateTimeField(verbose_name='Fecha consulta')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMC.Credito')),
            ],
        ),
    ]
